name: Verify Site Links

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 20
        cache: 'npm'

    - name: Install Dependencies
      run: npm install || true  # Runs successfully even if package-lock is empty

    - name: Run HTML Link Checkers
      run: npm test
